name: Deploy
on:
  push:
    branches: [ main, svelte ]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: ${{ github.ref_name == 'production' && 'production' || 'beta' }}
      url: ${{ github.ref_name == 'production' && 'https://traquantopassa.in' || 'https://traquantopassa-beta.fly.dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
